[project]
name = 'Luffie-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.deposit-management]
path = 'contracts/deposit-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.rental-agreement]
path = 'contracts/rental-agreement.clar'
clarity_version = 2
epoch = 2.5

[contracts.rental-listing]
path = 'contracts/rental-listing.clar'
clarity_version = 2
epoch = 2.5

[contracts.rental-payment-escrow]
path = 'contracts/rental-payment-escrow.clar'
clarity_version = 2
epoch = 2.5

[contracts.user-verification]
path = 'contracts/user-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
